{{- if and (not .Values.secrets.existingSecret) (not .Values.config.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quay-registry.secretName" . }}
  labels:
    {{- include "quay-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  DATABASE_SECRET_KEY: {{ .Values.secrets.databaseSecretKey | quote }}
  {{- if and (not .Values.database.existingSecret) .Values.database.uri }}
  DB_URI: {{ .Values.database.uri | quote }}
  {{- end }}
{{- end }}
