{{- if and .Values.clair.enabled (not .Values.clair.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quay-registry.fullname" . }}-clair-secret
  labels:
    {{- include "quay-registry.clairLabels" . | nindent 4 }}
type: Opaque
stringData:
  CLAIR_PSK_BASE64: {{ .Values.clair.auth.pskBase64 | quote }}
  {{- if and (not .Values.clair.database.existingSecret) .Values.clair.database.connstring }}
  CLAIR_DB_URI: {{ .Values.clair.database.connstring | quote }}
  {{- end }}
{{- end }}
